[versions]
agp = "8.14.0"
kotlin = "2.0.0"
kapt = "2.0.0"
hilt = "2.50"
gms = "4.4.1"
compose-bom = "2024.09.00"
firebase-bom = "33.1.0"
firebase-vertexai = "16.0.0"
core-ktx = "1.13.1"
appcompat = "1.7.0"
lifecycle-runtime-ktx = "2.8.4"
lifecycle-runtime-compose = "2.8.4"
activity-compose = "1.9.1"
ui = "1.7.0"
ui-tooling-preview = "1.7.0"
material3 = "1.2.1"
material = "1.12.0"
navigation-compose = "2.8.0"
hilt-navigation-compose = "1.2.0"
hilt-android = "2.50"
hilt-compiler = "2.50"
coroutines-core = "1.8.1"
coroutines-android = "1.8.1"
room-runtime = "2.6.1"
room-ktx = "2.6.1"
room-compiler = "2.6.1"
work-runtime-ktx = "2.9.0"
datastore-preferences = "1.1.1"
retrofit = "2.9.0"
converter-moshi = "2.9.0"
moshi-kotlin = "1.15.0"
moshi-codegen = "1.15.0"
logging-interceptor = "4.12.0"
timber = "5.0.1"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso-core = "3.5.1"
ui-test-junit4 = "1.7.0"
ui-tooling = "1.7.0"
ui-test-manifest = "1.7.0"
compose-compiler = "1.5.14"

[plugins]
agp-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
kotlin-parcelize = { id = "kotlin-parcelize", version.ref = "kotlin" }

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-vertexai = { group = "com.google.firebase", name = "firebase-vertexai", version.ref = "firebase-vertexai" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-compiler" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-core" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-runtime" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-ktx" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converter-moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi-codegen" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "ui-test-manifest" }